In [0]:
import pandas as pd
import numpy as np

In [0]:
spark.sql("USE CATALOG 'proyecto_final_prueba'")

DataFrame[]

In [0]:
catalog = spark.sql("SELECT current_catalog()").first()[0]
schema = 'silver'
table = 'weather'

In [0]:
spark.sql(f"create schema if not exists {catalog}.{schema}")

DataFrame[]

In [0]:
spark.sql(f"drop table if exists {catalog}.{schema}.{table}")

DataFrame[]

In [0]:
spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.{table} (
  fecha_hora_local TIMESTAMP,
  latitude DOUBLE,
  longitude DOUBLE,
  temperature DOUBLE,
  humidity INT,
  wind_speed DOUBLE,
  weather_code INT,
  weather_desc STRING
)
""")

DataFrame[]

In [0]:
df = spark.table(f"{catalog}.bronze.{table}").toPandas()
df

      latitude  ...                                hourly.weather_code
0   -12.056238  ...  [2, 2, 3, 51, 2, 2, 3, 1, 0, 0, 0, 0, 1, 2, 0,...
1   -12.056238  ...  [61, 3, 3, 3, 51, 51, 61, 61, 51, 2, 2, 3, 3, ...
2   -12.056238  ...  [51, 3, 3, 3, 3, 3, 51, 51, 3, 3, 3, 3, 3, 1, ...
3   -12.056238  ...  [63, 51, 3, 3, 51, 51, 3, 3, 3, 3, 3, 2, 2, 51...
4   -12.056238  ...  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 51, 3, 3, 3, 3,...
..         ...  ...                                                ...
222 -12.056238  ...  [1, 1, 1, 1, 2, 3, 3, 3, 2, 2, 2, 2, 1, 1, 2, ...
223 -12.056238  ...  [1, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 2, ...
224 -12.056238  ...  [3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, ...
225 -12.056238  ...  [2, 2, 2, 1, 0, 0, 1, 2, 3, 3, 3, 3, 1, 0, 0, ...
226 -12.056238  ...  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 3, 3, 3, ...

[227 rows x 17 columns]

In [0]:
columns_list =['hourly.time', 'hourly.temperature_2m', 'hourly.relative_humidity_2m', 'hourly.wind_speed_10m', 'hourly.weather_code']
df_silver = df.explode(columns_list)
df_silver

      latitude  longitude  ...  hourly.wind_speed_10m  hourly.weather_code
0   -12.056238  -77.06198  ...                    9.8                    2
0   -12.056238  -77.06198  ...                    8.9                    2
0   -12.056238  -77.06198  ...                    7.7                    3
0   -12.056238  -77.06198  ...                    6.2                   51
0   -12.056238  -77.06198  ...                    5.2                    2
..         ...        ...  ...                    ...                  ...
226 -12.056238  -77.06198  ...                    9.6                    0
226 -12.056238  -77.06198  ...                    6.7                    0
226 -12.056238  -77.06198  ...                    8.2                    0
226 -12.056238  -77.06198  ...                    9.7                    3
226 -12.056238  -77.06198  ...                    9.4                    3

[5448 rows x 17 columns]

In [0]:
rename_col = {'hourly.time': 'time',
    'hourly.temperature_2m': 'temperature',
    'hourly.relative_humidity_2m': 'humidity',
    'hourly.wind_speed_10m': 'wind_speed',
    'hourly.weather_code': 'weather_code'}

df_silver = df_silver.rename(columns=rename_col)
df_silver

      latitude  longitude  generationtime_ms  ...  humidity wind_speed weather_code
0   -12.056238  -77.06198           7.394552  ...        82        9.8            2
0   -12.056238  -77.06198           7.394552  ...        83        8.9            2
0   -12.056238  -77.06198           7.394552  ...        80        7.7            3
0   -12.056238  -77.06198           7.394552  ...        79        6.2           51
0   -12.056238  -77.06198           7.394552  ...        80        5.2            2
..         ...        ...                ...  ...       ...        ...          ...
226 -12.056238  -77.06198           0.236273  ...        73        9.6            0
226 -12.056238  -77.06198           0.236273  ...        72        6.7            0
226 -12.056238  -77.06198           0.236273  ...        71        8.2            0
226 -12.056238  -77.06198           0.236273  ...        74        9.7            3
226 -12.056238  -77.06198           0.236273  ...        77        9.4            3

[5448 rows x 17 columns]

In [0]:
df_silver['temperature'] = df_silver['temperature'].astype(float)
df_silver['wind_speed'] = df_silver['wind_speed'].astype(float)
df_silver['humidity'] = df_silver['humidity'].astype(int)
df_silver['weather_code'] = df_silver['weather_code'].astype(int)

df_silver['fecha_hora_utc'] = pd.to_datetime(df_silver['time'])
df_silver['fecha_hora_local'] = df_silver['fecha_hora_utc'] - pd.Timedelta(hours=5)
df_silver

      latitude  longitude  ...      fecha_hora_utc    fecha_hora_local
0   -12.056238  -77.06198  ... 2026-01-01 00:00:00 2025-12-31 19:00:00
0   -12.056238  -77.06198  ... 2026-01-01 01:00:00 2025-12-31 20:00:00
0   -12.056238  -77.06198  ... 2026-01-01 02:00:00 2025-12-31 21:00:00
0   -12.056238  -77.06198  ... 2026-01-01 03:00:00 2025-12-31 22:00:00
0   -12.056238  -77.06198  ... 2026-01-01 04:00:00 2025-12-31 23:00:00
..         ...        ...  ...                 ...                 ...
226 -12.056238  -77.06198  ... 2026-08-09 19:00:00 2026-08-09 14:00:00
226 -12.056238  -77.06198  ... 2026-08-09 20:00:00 2026-08-09 15:00:00
226 -12.056238  -77.06198  ... 2026-08-09 21:00:00 2026-08-09 16:00:00
226 -12.056238  -77.06198  ... 2026-08-09 22:00:00 2026-08-09 17:00:00
226 -12.056238  -77.06198  ... 2026-08-09 23:00:00 2026-08-09 18:00:00

[5448 rows x 19 columns]

In [0]:
condiciones = [
    (df_silver['weather_code'] == 0),
    (df_silver['weather_code'].between(1, 3)),
    (df_silver['weather_code'].between(51, 69))
]
valores = ['Despejado', 'Nublado', 'Lluvia ligera/moderada']
df_silver['weather_desc'] = np.select(condiciones, valores, default='Otro / Extremo')
df_silver

      latitude  longitude  ...    fecha_hora_local            weather_desc
0   -12.056238  -77.06198  ... 2025-12-31 19:00:00                 Nublado
0   -12.056238  -77.06198  ... 2025-12-31 20:00:00                 Nublado
0   -12.056238  -77.06198  ... 2025-12-31 21:00:00                 Nublado
0   -12.056238  -77.06198  ... 2025-12-31 22:00:00  Lluvia ligera/moderada
0   -12.056238  -77.06198  ... 2025-12-31 23:00:00                 Nublado
..         ...        ...  ...                 ...                     ...
226 -12.056238  -77.06198  ... 2026-08-09 14:00:00               Despejado
226 -12.056238  -77.06198  ... 2026-08-09 15:00:00               Despejado
226 -12.056238  -77.06198  ... 2026-08-09 16:00:00               Despejado
226 -12.056238  -77.06198  ... 2026-08-09 17:00:00                 Nublado
226 -12.056238  -77.06198  ... 2026-08-09 18:00:00                 Nublado

[5448 rows x 20 columns]

In [0]:
df_silver = df_silver.drop_duplicates(subset=['fecha_hora_local'])
df_silver = df_silver.dropna(subset=['temperature'])

columnas_finales = [
    'fecha_hora_local', 'latitude', 'longitude', 'temperature', 
    'humidity', 'wind_speed', 'weather_code', 'weather_desc'
]
df_silver = df_silver[columnas_finales]
df_silver

       fecha_hora_local   latitude  ...  weather_code            weather_desc
0   2025-12-31 19:00:00 -12.056238  ...             2                 Nublado
0   2025-12-31 20:00:00 -12.056238  ...             2                 Nublado
0   2025-12-31 21:00:00 -12.056238  ...             3                 Nublado
0   2025-12-31 22:00:00 -12.056238  ...            51  Lluvia ligera/moderada
0   2025-12-31 23:00:00 -12.056238  ...             2                 Nublado
..                  ...        ...  ...           ...                     ...
226 2026-08-09 14:00:00 -12.056238  ...             0               Despejado
226 2026-08-09 15:00:00 -12.056238  ...             0               Despejado
226 2026-08-09 16:00:00 -12.056238  ...             0               Despejado
226 2026-08-09 17:00:00 -12.056238  ...             3                 Nublado
226 2026-08-09 18:00:00 -12.056238  ...             3                 Nublado

[5448 rows x 8 columns]

In [0]:
df_spark = spark.createDataFrame(df_silver)
df_spark.display()

fecha_hora_local,latitude,longitude,temperature,humidity,wind_speed,weather_code,weather_desc
2025-12-31T19:00:00.000Z,-12.056238,-77.06198,19.9,82,9.8,2,Nublado
2025-12-31T20:00:00.000Z,-12.056238,-77.06198,19.4,83,8.9,2,Nublado
2025-12-31T21:00:00.000Z,-12.056238,-77.06198,19.6,80,7.7,3,Nublado
2025-12-31T22:00:00.000Z,-12.056238,-77.06198,19.8,79,6.2,51,Lluvia ligera/moderada
2025-12-31T23:00:00.000Z,-12.056238,-77.06198,19.8,80,5.2,2,Nublado
2026-01-01T00:00:00.000Z,-12.056238,-77.06198,19.5,81,5.1,2,Nublado
2026-01-01T01:00:00.000Z,-12.056238,-77.06198,18.9,86,2.6,3,Nublado
2026-01-01T02:00:00.000Z,-12.056238,-77.06198,18.5,90,3.9,1,Nublado
2026-01-01T03:00:00.000Z,-12.056238,-77.06198,18.1,92,4.7,0,Despejado
2026-01-01T04:00:00.000Z,-12.056238,-77.06198,17.8,94,2.8,0,Despejado
2026-01-01T05:00:00.000Z,-12.056238,-77.06198,17.7,94,2.6,0,Despejado
2026-01-01T06:00:00.000Z,-12.056238,-77.06198,17.7,94,2.5,0,Despejado
2026-01-01T07:00:00.000Z,-12.056238,-77.06198,18.4,92,3.8,1,Nublado
2026-01-01T08:00:00.000Z,-12.056238,-77.06198,20.1,82,5.6,2,Nublado
2026-01-01T09:00:00.000Z,-12.056238,-77.06198,21.6,75,7.6,0,Despejado
2026-01-01T10:00:00.000Z,-12.056238,-77.06198,22.0,74,11.1,1,Nublado
2026-01-01T11:00:00.000Z,-12.056238,-77.06198,21.7,74,12.0,3,Nublado
2026-01-01T12:00:00.000Z,-12.056238,-77.06198,21.7,73,11.6,3,Nublado
2026-01-01T13:00:00.000Z,-12.056238,-77.06198,21.7,71,9.2,3,Nublado
2026-01-01T14:00:00.000Z,-12.056238,-77.06198,22.0,69,6.7,3,Nublado
2026-01-01T15:00:00.000Z,-12.056238,-77.06198,22.4,67,5.9,3,Nublado
2026-01-01T16:00:00.000Z,-12.056238,-77.06198,22.5,69,11.0,2,Nublado
2026-01-01T17:00:00.000Z,-12.056238,-77.06198,21.6,74,10.6,3,Nublado
2026-01-01T18:00:00.000Z,-12.056238,-77.06198,21.1,76,11.1,2,Nublado
2026-01-09T19:00:00.000Z,-12.056238,-77.06198,21.4,82,3.8,61,Lluvia ligera/moderada
2026-01-09T20:00:00.000Z,-12.056238,-77.06198,21.2,83,2.8,3,Nublado
2026-01-09T21:00:00.000Z,-12.056238,-77.06198,21.1,83,1.7,3,Nublado
2026-01-09T22:00:00.000Z,-12.056238,-77.06198,21.2,83,2.2,3,Nublado
2026-01-09T23:00:00.000Z,-12.056238,-77.06198,20.7,86,3.3,51,Lluvia ligera/moderada
2026-01-10T00:00:00.000Z,-12.056238,-77.06198,20.4,89,4.0,51,Lluvia ligera/moderada
2026-01-10T01:00:00.000Z,-12.056238,-77.06198,20.4,97,4.7,61,Lluvia ligera/moderada
2026-01-10T02:00:00.000Z,-12.056238,-77.06198,20.2,98,6.0,61,Lluvia ligera/moderada
2026-01-10T03:00:00.000Z,-12.056238,-77.06198,20.0,98,4.5,51,Lluvia ligera/moderada
2026-01-10T04:00:00.000Z,-12.056238,-77.06198,19.9,98,4.6,2,Nublado
2026-01-10T05:00:00.000Z,-12.056238,-77.06198,19.9,98,3.3,2,Nublado
2026-01-10T06:00:00.000Z,-12.056238,-77.06198,20.2,97,1.8,3,Nublado
2026-01-10T07:00:00.000Z,-12.056238,-77.06198,20.7,92,2.3,3,Nublado
2026-01-10T08:00:00.000Z,-12.056238,-77.06198,21.0,91,2.2,3,Nublado
2026-01-10T09:00:00.000Z,-12.056238,-77.06198,22.2,86,2.5,3,Nublado
2026-01-10T10:00:00.000Z,-12.056238,-77.06198,22.8,83,6.3,3,Nublado
2026-01-10T11:00:00.000Z,-12.056238,-77.06198,22.1,85,8.9,3,Nublado
2026-01-10T12:00:00.000Z,-12.056238,-77.06198,21.8,86,4.4,3,Nublado
2026-01-10T13:00:00.000Z,-12.056238,-77.06198,21.7,83,4.1,3,Nublado
2026-01-10T14:00:00.000Z,-12.056238,-77.06198,22.0,83,3.8,3,Nublado
2026-01-10T15:00:00.000Z,-12.056238,-77.06198,22.1,82,4.2,3,Nublado
2026-01-10T16:00:00.000Z,-12.056238,-77.06198,21.6,84,5.6,3,Nublado
2026-01-10T17:00:00.000Z,-12.056238,-77.06198,21.1,87,5.9,3,Nublado
2026-01-10T18:00:00.000Z,-12.056238,-77.06198,21.0,90,4.3,51,Lluvia ligera/moderada
2026-01-10T19:00:00.000Z,-12.056238,-77.06198,21.2,89,5.2,51,Lluvia ligera/moderada
2026-01-10T20:00:00.000Z,-12.056238,-77.06198,20.8,93,5.9,3,Nublado
2026-01-10T21:00:00.000Z,-12.056238,-77.06198,20.7,94,4.8,3,Nublado
2026-01-10T22:00:00.000Z,-12.056238,-77.06198,20.6,95,3.1,3,Nublado
2026-01-10T23:00:00.000Z,-12.056238,-77.06198,20.5,96,3.2,3,Nublado
2026-01-11T00:00:00.000Z,-12.056238,-77.06198,20.4,97,4.4,3,Nublado
2026-01-11T01:00:00.000Z,-12.056238,-77.06198,20.4,98,4.0,51,Lluvia ligera/moderada
2026-01-11T02:00:00.000Z,-12.056238,-77.06198,20.4,97,3.6,51,Lluvia ligera/moderada
2026-01-11T03:00:00.000Z,-12.056238,-77.06198,20.3,95,5.4,3,Nublado
2026-01-11T04:00:00.000Z,-12.056238,-77.06198,20.3,93,6.0,3,Nublado
2026-01-11T05:00:00.000Z,-12.056238,-77.06198,20.2,91,4.2,3,Nublado
2026-01-11T06:00:00.000Z,-12.056238,-77.06198,20.1,90,2.2,3,Nublado
2026-01-11T07:00:00.000Z,-12.056238,-77.06198,20.7,92,3.0,3,Nublado
2026-01-11T08:00:00.000Z,-12.056238,-77.06198,21.8,90,5.2,1,Nublado
2026-01-11T09:00:00.000Z,-12.056238,-77.06198,22.4,86,7.4,0,Despejado
2026-01-11T10:00:00.000Z,-12.056238,-77.06198,22.7,83,8.7,0,Despejado
2026-01-11T11:00:00.000Z,-12.056238,-77.06198,22.5,85,9.1,0,Despejado
2026-01-11T12:00:00.000Z,-12.056238,-77.06198,22.4,88,7.8,0,Despejado
2026-01-11T13:00:00.000Z,-12.056238,-77.06198,22.9,85,8.5,0,Despejado
2026-01-11T14:00:00.000Z,-12.056238,-77.06198,23.2,82,7.5,0,Despejado
2026-01-11T15:00:00.000Z,-12.056238,-77.06198,22.9,79,8.2,2,Nublado
2026-01-11T16:00:00.000Z,-12.056238,-77.06198,22.1,81,6.1,2,Nublado
2026-01-11T17:00:00.000Z,-12.056238,-77.06198,21.7,81,6.1,3,Nublado
2026-01-11T18:00:00.000Z,-12.056238,-77.06198,21.1,86,5.3,55,Lluvia ligera/moderada
2026-01-11T19:00:00.000Z,-12.056238,-77.06198,20.8,94,7.5,63,Lluvia ligera/moderada
2026-01-11T20:00:00.000Z,-12.056238,-77.06198,21.0,95,8.0,51,Lluvia ligera/moderada
2026-01-11T21:00:00.000Z,-12.056238,-77.06198,21.1,94,7.6,3,Nublado
2026-01-11T22:00:00.000Z,-12.056238,-77.06198,21.3,91,8.8,3,Nublado
2026-01-11T23:00:00.000Z,-12.056238,-77.06198,21.2,91,8.3,51,Lluvia ligera/moderada
2026-01-12T00:00:00.000Z,-12.056238,-77.06198,21.1,91,9.4,51,Lluvia ligera/moderada
2026-01-12T01:00:00.000Z,-12.056238,-77.06198,21.0,91,7.5,3,Nublado
2026-01-12T02:00:00.000Z,-12.056238,-77.06198,21.0,91,7.0,3,Nublado
2026-01-12T03:00:00.000Z,-12.056238,-77.06198,20.8,91,6.0,3,Nublado
2026-01-12T04:00:00.000Z,-12.056238,-77.06198,20.7,91,4.9,3,Nublado
2026-01-12T05:00:00.000Z,-12.056238,-77.06198,20.4,93,4.5,3,Nublado
2026-01-12T06:00:00.000Z,-12.056238,-77.06198,20.3,92,6.9,2,Nublado
2026-01-12T07:00:00.000Z,-12.056238,-77.06198,21.1,94,4.8,2,Nublado
2026-01-12T08:00:00.000Z,-12.056238,-77.06198,22.3,86,4.9,51,Lluvia ligera/moderada
2026-01-12T09:00:00.000Z,-12.056238,-77.06198,23.0,85,6.6,2,Nublado
2026-01-12T10:00:00.000Z,-12.056238,-77.06198,22.7,88,8.3,3,Nublado
2026-01-12T11:00:00.000Z,-12.056238,-77.06198,23.0,87,8.5,3,Nublado
2026-01-12T12:00:00.000Z,-12.056238,-77.06198,23.3,85,8.6,2,Nublado
2026-01-12T13:00:00.000Z,-12.056238,-77.06198,23.6,87,9.3,2,Nublado
2026-01-12T14:00:00.000Z,-12.056238,-77.06198,23.4,89,8.9,3,Nublado
2026-01-12T15:00:00.000Z,-12.056238,-77.06198,23.5,85,6.6,3,Nublado
2026-01-12T16:00:00.000Z,-12.056238,-77.06198,23.3,79,7.8,3,Nublado
2026-01-12T17:00:00.000Z,-12.056238,-77.06198,22.6,83,6.2,3,Nublado
2026-01-12T18:00:00.000Z,-12.056238,-77.06198,21.8,87,3.8,3,Nublado
2026-01-12T19:00:00.000Z,-12.056238,-77.06198,21.2,89,2.3,3,Nublado
2026-01-12T20:00:00.000Z,-12.056238,-77.06198,21.0,91,4.2,3,Nublado
2026-01-12T21:00:00.000Z,-12.056238,-77.06198,20.8,91,2.3,3,Nublado
2026-01-12T22:00:00.000Z,-12.056238,-77.06198,20.9,91,2.0,3,Nublado
2026-01-12T23:00:00.000Z,-12.056238,-77.06198,20.8,91,4.2,3,Nublado
2026-01-13T00:00:00.000Z,-12.056238,-77.06198,20.6,92,3.2,3,Nublado
2026-01-13T01:00:00.000Z,-12.056238,-77.06198,20.6,94,4.4,3,Nublado
2026-01-13T02:00:00.000Z,-12.056238,-77.06198,20.5,95,2.5,3,Nublado
2026-01-13T03:00:00.000Z,-12.056238,-77.06198,20.2,95,1.4,3,Nublado
2026-01-13T04:00:00.000Z,-12.056238,-77.06198,20.0,96,0.8,3,Nublado
2026-01-13T05:00:00.000Z,-12.056238,-77.06198,20.3,93,2.9,51,Lluvia ligera/moderada
2026-01-13T06:00:00.000Z,-12.056238,-77.06198,20.5,90,3.6,3,Nublado
2026-01-13T07:00:00.000Z,-12.056238,-77.06198,20.7,93,4.0,3,Nublado
2026-01-13T08:00:00.000Z,-12.056238,-77.06198,21.5,91,2.9,3,Nublado
2026-01-13T09:00:00.000Z,-12.056238,-77.06198,22.1,89,3.3,3,Nublado
2026-01-13T10:00:00.000Z,-12.056238,-77.06198,22.7,87,6.5,3,Nublado
2026-01-13T11:00:00.000Z,-12.056238,-77.06198,22.9,87,8.8,3,Nublado
2026-01-13T12:00:00.000Z,-12.056238,-77.06198,22.7,86,9.6,3,Nublado
2026-01-13T13:00:00.000Z,-12.056238,-77.06198,23.6,80,8.2,3,Nublado
2026-01-13T14:00:00.000Z,-12.056238,-77.06198,23.1,83,5.3,3,Nublado
2026-01-13T15:00:00.000Z,-12.056238,-77.06198,23.0,86,5.8,3,Nublado
2026-01-13T16:00:00.000Z,-12.056238,-77.06198,22.8,87,6.4,3,Nublado
2026-01-13T17:00:00.000Z,-12.056238,-77.06198,22.3,90,6.4,3,Nublado
2026-01-13T18:00:00.000Z,-12.056238,-77.06198,21.9,91,6.1,3,Nublado
2026-01-13T19:00:00.000Z,-12.056238,-77.06198,22.2,90,5.0,3,Nublado
2026-01-13T20:00:00.000Z,-12.056238,-77.06198,22.1,90,6.2,3,Nublado
2026-01-13T21:00:00.000Z,-12.056238,-77.06198,22.0,90,5.8,3,Nublado
2026-01-13T22:00:00.000Z,-12.056238,-77.06198,21.6,91,5.6,3,Nublado
2026-01-13T23:00:00.000Z,-12.056238,-77.06198,21.2,93,5.6,3,Nublado
2026-01-14T00:00:00.000Z,-12.056238,-77.06198,21.0,94,4.7,3,Nublado
2026-01-14T01:00:00.000Z,-12.056238,-77.06198,21.4,91,5.6,3,Nublado
2026-01-14T02:00:00.000Z,-12.056238,-77.06198,21.3,91,5.9,3,Nublado
2026-01-14T03:00:00.000Z,-12.056238,-77.06198,21.2,91,6.4,3,Nublado
2026-01-14T04:00:00.000Z,-12.056238,-77.06198,21.1,91,6.9,3,Nublado
2026-01-14T05:00:00.000Z,-12.056238,-77.06198,21.0,91,7.4,3,Nublado
2026-01-14T06:00:00.000Z,-12.056238,-77.06198,20.9,91,7.5,3,Nublado
2026-01-14T07:00:00.000Z,-12.056238,-77.06198,21.3,91,6.9,3,Nublado
2026-01-14T08:00:00.000Z,-12.056238,-77.06198,22.2,87,7.0,3,Nublado
2026-01-14T09:00:00.000Z,-12.056238,-77.06198,23.6,81,8.6,3,Nublado
2026-01-14T10:00:00.000Z,-12.056238,-77.06198,24.1,80,10.4,3,Nublado
2026-01-14T11:00:00.000Z,-12.056238,-77.06198,24.5,76,11.9,2,Nublado
2026-01-14T12:00:00.000Z,-12.056238,-77.06198,24.3,76,11.2,3,Nublado
2026-01-14T13:00:00.000Z,-12.056238,-77.06198,24.5,73,11.1,2,Nublado
2026-01-14T14:00:00.000Z,-12.056238,-77.06198,24.4,76,12.6,3,Nublado
2026-01-14T15:00:00.000Z,-12.056238,-77.06198,24.0,77,11.6,3,Nublado
2026-01-14T16:00:00.000Z,-12.056238,-77.06198,23.5,77,10.9,3,Nublado
2026-01-14T17:00:00.000Z,-12.056238,-77.06198,23.2,77,12.1,3,Nublado
2026-01-14T18:00:00.000Z,-12.056238,-77.06198,23.0,77,13.8,3,Nublado
2026-01-14T19:00:00.000Z,-12.056238,-77.06198,22.6,79,12.4,3,Nublado
2026-01-14T20:00:00.000Z,-12.056238,-77.06198,22.3,81,12.9,3,Nublado
2026-01-14T21:00:00.000Z,-12.056238,-77.06198,22.2,82,13.8,1,Nublado
2026-01-14T22:00:00.000Z,-12.056238,-77.06198,21.8,84,14.7,2,Nublado
2026-01-14T23:00:00.000Z,-12.056238,-77.06198,21.5,84,13.2,51,Lluvia ligera/moderada
2026-01-15T00:00:00.000Z,-12.056238,-77.06198,21.4,84,12.8,51,Lluvia ligera/moderada
2026-01-15T01:00:00.000Z,-12.056238,-77.06198,21.6,82,6.9,53,Lluvia ligera/moderada
2026-01-15T02:00:00.000Z,-12.056238,-77.06198,21.5,82,6.9,51,Lluvia ligera/moderada
2026-01-15T03:00:00.000Z,-12.056238,-77.06198,20.7,89,6.1,55,Lluvia ligera/moderada
2026-01-15T04:00:00.000Z,-12.056238,-77.06198,20.2,95,4.9,55,Lluvia ligera/moderada
2026-01-15T05:00:00.000Z,-12.056238,-77.06198,19.8,97,7.0,53,Lluvia ligera/moderada
2026-01-15T06:00:00.000Z,-12.056238,-77.06198,19.6,97,2.5,51,Lluvia ligera/moderada
2026-01-15T07:00:00.000Z,-12.056238,-77.06198,20.7,93,4.7,2,Nublado
2026-01-15T08:00:00.000Z,-12.056238,-77.06198,21.5,88,2.9,1,Nublado
2026-01-15T09:00:00.000Z,-12.056238,-77.06198,22.9,78,3.6,1,Nublado
2026-01-15T10:00:00.000Z,-12.056238,-77.06198,23.4,75,8.2,1,Nublado
2026-01-15T11:00:00.000Z,-12.056238,-77.06198,23.6,73,6.7,2,Nublado
2026-01-15T12:00:00.000Z,-12.056238,-77.06198,24.0,70,9.0,3,Nublado
2026-01-15T13:00:00.000Z,-12.056238,-77.06198,23.6,69,8.2,3,Nublado
2026-01-15T14:00:00.000Z,-12.056238,-77.06198,23.9,67,7.9,3,Nublado
2026-01-15T15:00:00.000Z,-12.056238,-77.06198,23.4,71,4.4,3,Nublado
2026-01-15T16:00:00.000Z,-12.056238,-77.06198,23.5,72,6.5,3,Nublado
2026-01-15T17:00:00.000Z,-12.056238,-77.06198,23.0,77,5.5,3,Nublado
2026-01-15T18:00:00.000Z,-12.056238,-77.06198,22.4,82,4.9,3,Nublado
2026-01-15T19:00:00.000Z,-12.056238,-77.06198,21.7,84,4.1,3,Nublado
2026-01-15T20:00:00.000Z,-12.056238,-77.06198,21.5,85,4.0,3,Nublado
2026-01-15T21:00:00.000Z,-12.056238,-77.06198,21.2,87,2.8,3,Nublado
2026-01-15T22:00:00.000Z,-12.056238,-77.06198,21.0,89,2.2,3,Nublado
2026-01-15T23:00:00.000Z,-12.056238,-77.06198,20.9,89,3.6,3,Nublado
2026-01-16T00:00:00.000Z,-12.056238,-77.06198,21.2,88,1.3,3,Nublado
2026-01-16T01:00:00.000Z,-12.056238,-77.06198,21.4,91,4.9,51,Lluvia ligera/moderada
2026-01-16T02:00:00.000Z,-12.056238,-77.06198,21.3,93,4.8,53,Lluvia ligera/moderada
2026-01-16T03:00:00.000Z,-12.056238,-77.06198,21.0,95,3.1,53,Lluvia ligera/moderada
2026-01-16T04:00:00.000Z,-12.056238,-77.06198,20.6,95,0.5,3,Nublado
2026-01-16T05:00:00.000Z,-12.056238,-77.06198,20.4,97,1.7,3,Nublado
2026-01-16T06:00:00.000Z,-12.056238,-77.06198,20.2,98,1.5,1,Nublado
2026-01-16T07:00:00.000Z,-12.056238,-77.06198,20.7,96,5.1,3,Nublado
2026-01-16T08:00:00.000Z,-12.056238,-77.06198,22.2,81,4.3,3,Nublado
2026-01-16T09:00:00.000Z,-12.056238,-77.06198,23.4,72,6.3,3,Nublado
2026-01-16T10:00:00.000Z,-12.056238,-77.06198,24.2,69,8.9,3,Nublado
2026-01-16T11:00:00.000Z,-12.056238,-77.06198,24.4,71,11.2,1,Nublado
2026-01-16T12:00:00.000Z,-12.056238,-77.06198,24.3,71,14.6,0,Despejado
2026-01-16T13:00:00.000Z,-12.056238,-77.06198,24.6,69,11.3,3,Nublado
2026-01-16T14:00:00.000Z,-12.056238,-77.06198,24.4,68,11.3,3,Nublado
2026-01-16T15:00:00.000Z,-12.056238,-77.06198,23.3,79,11.2,3,Nublado
2026-01-16T16:00:00.000Z,-12.056238,-77.06198,23.0,83,10.7,3,Nublado
2026-01-16T17:00:00.000Z,-12.056238,-77.06198,22.6,83,11.1,3,Nublado
2026-01-16T18:00:00.000Z,-12.056238,-77.06198,22.3,82,11.5,3,Nublado
2026-01-16T19:00:00.000Z,-12.056238,-77.06198,21.9,84,14.6,3,Nublado
2026-01-16T20:00:00.000Z,-12.056238,-77.06198,21.8,87,15.3,51,Lluvia ligera/moderada
2026-01-16T21:00:00.000Z,-12.056238,-77.06198,21.6,88,14.3,3,Nublado
2026-01-16T22:00:00.000Z,-12.056238,-77.06198,21.6,87,14.0,3,Nublado
2026-01-16T23:00:00.000Z,-12.056238,-77.06198,21.5,87,11.5,3,Nublado
2026-01-17T00:00:00.000Z,-12.056238,-77.06198,21.5,86,7.9,3,Nublado
2026-01-17T01:00:00.000Z,-12.056238,-77.06198,21.7,87,3.4,51,Lluvia ligera/moderada
2026-01-17T02:00:00.000Z,-12.056238,-77.06198,21.3,90,4.7,3,Nublado
2026-01-17T03:00:00.000Z,-12.056238,-77.06198,20.7,93,6.7,3,Nublado
2026-01-17T04:00:00.000Z,-12.056238,-77.06198,20.6,93,3.7,3,Nublado
2026-01-17T05:00:00.000Z,-12.056238,-77.06198,20.2,95,1.3,53,Lluvia ligera/moderada
2026-01-17T06:00:00.000Z,-12.056238,-77.06198,20.1,95,0.6,3,Nublado
2026-01-17T07:00:00.000Z,-12.056238,-77.06198,20.7,97,2.1,3,Nublado
2026-01-17T08:00:00.000Z,-12.056238,-77.06198,21.2,91,3.7,3,Nublado
2026-01-17T09:00:00.000Z,-12.056238,-77.06198,22.3,84,4.7,3,Nublado
2026-01-17T10:00:00.000Z,-12.056238,-77.06198,23.2,78,5.8,3,Nublado
2026-01-17T11:00:00.000Z,-12.056238,-77.06198,23.6,78,6.6,3,Nublado
2026-01-17T12:00:00.000Z,-12.056238,-77.06198,23.3,80,8.7,3,Nublado
2026-01-17T13:00:00.000Z,-12.056238,-77.06198,23.6,79,9.5,3,Nublado
2026-01-17T14:00:00.000Z,-12.056238,-77.06198,23.7,80,6.5,3,Nublado
2026-01-17T15:00:00.000Z,-12.056238,-77.06198,23.9,78,8.9,3,Nublado
2026-01-17T16:00:00.000Z,-12.056238,-77.06198,23.2,77,12.4,3,Nublado
2026-01-17T17:00:00.000Z,-12.056238,-77.06198,22.5,83,13.3,3,Nublado
2026-01-17T18:00:00.000Z,-12.056238,-77.06198,22.1,86,8.9,3,Nublado
2026-01-17T19:00:00.000Z,-12.056238,-77.06198,21.3,88,10.1,3,Nublado
2026-01-17T20:00:00.000Z,-12.056238,-77.06198,21.1,88,12.1,53,Lluvia ligera/moderada
2026-01-17T21:00:00.000Z,-12.056238,-77.06198,21.1,88,14.7,3,Nublado
2026-01-17T22:00:00.000Z,-12.056238,-77.06198,21.0,88,13.9,3,Nublado
2026-01-17T23:00:00.000Z,-12.056238,-77.06198,21.0,88,13.8,3,Nublado
2026-01-18T00:00:00.000Z,-12.056238,-77.06198,20.8,89,12.1,3,Nublado
2026-01-18T01:00:00.000Z,-12.056238,-77.06198,21.3,88,2.8,3,Nublado
2026-01-18T02:00:00.000Z,-12.056238,-77.06198,21.1,89,1.5,3,Nublado
2026-01-18T03:00:00.000Z,-12.056238,-77.06198,20.8,91,3.0,3,Nublado
2026-01-18T04:00:00.000Z,-12.056238,-77.06198,20.4,93,5.0,3,Nublado
2026-01-18T05:00:00.000Z,-12.056238,-77.06198,20.1,95,6.1,3,Nublado
2026-01-18T06:00:00.000Z,-12.056238,-77.06198,19.7,98,7.8,3,Nublado
2026-01-18T07:00:00.000Z,-12.056238,-77.06198,20.7,93,2.4,3,Nublado
2026-01-18T08:00:00.000Z,-12.056238,-77.06198,22.0,85,2.3,3,Nublado
2026-01-18T09:00:00.000Z,-12.056238,-77.06198,23.0,80,5.6,3,Nublado
2026-01-18T10:00:00.000Z,-12.056238,-77.06198,23.6,78,6.9,3,Nublado
2026-01-18T11:00:00.000Z,-12.056238,-77.06198,23.8,77,8.9,3,Nublado
2026-01-18T12:00:00.000Z,-12.056238,-77.06198,23.7,76,8.1,3,Nublado
2026-01-18T13:00:00.000Z,-12.056238,-77.06198,23.6,76,10.9,3,Nublado
2026-01-18T14:00:00.000Z,-12.056238,-77.06198,23.8,75,7.0,3,Nublado
2026-01-18T15:00:00.000Z,-12.056238,-77.06198,24.2,73,6.8,3,Nublado
2026-01-18T16:00:00.000Z,-12.056238,-77.06198,23.5,76,7.0,3,Nublado
2026-01-18T17:00:00.000Z,-12.056238,-77.06198,22.7,79,6.3,3,Nublado
2026-01-18T18:00:00.000Z,-12.056238,-77.06198,21.8,86,5.1,3,Nublado
2026-01-18T19:00:00.000Z,-12.056238,-77.06198,21.7,88,6.6,3,Nublado
2026-01-18T20:00:00.000Z,-12.056238,-77.06198,21.7,89,5.6,3,Nublado
2026-01-18T21:00:00.000Z,-12.056238,-77.06198,21.6,85,8.1,2,Nublado
2026-01-18T22:00:00.000Z,-12.056238,-77.06198,21.3,85,9.4,2,Nublado
2026-01-18T23:00:00.000Z,-12.056238,-77.06198,21.0,86,6.5,3,Nublado
2026-01-19T00:00:00.000Z,-12.056238,-77.06198,21.0,87,4.0,3,Nublado
2026-01-19T01:00:00.000Z,-12.056238,-77.06198,20.9,88,6.6,3,Nublado
2026-01-19T02:00:00.000Z,-12.056238,-77.06198,21.2,86,8.4,3,Nublado
2026-01-19T03:00:00.000Z,-12.056238,-77.06198,21.5,84,8.4,3,Nublado
2026-01-19T04:00:00.000Z,-12.056238,-77.06198,21.4,84,7.4,3,Nublado
2026-01-19T05:00:00.000Z,-12.056238,-77.06198,21.1,86,6.6,2,Nublado
2026-01-19T06:00:00.000Z,-12.056238,-77.06198,20.8,87,7.5,1,Nublado
2026-01-19T07:00:00.000Z,-12.056238,-77.06198,21.2,84,5.4,1,Nublado
2026-01-19T08:00:00.000Z,-12.056238,-77.06198,22.5,78,7.3,3,Nublado
2026-01-19T09:00:00.000Z,-12.056238,-77.06198,23.1,75,9.2,1,Nublado
2026-01-19T10:00:00.000Z,-12.056238,-77.06198,24.0,72,10.3,1,Nublado
2026-01-19T11:00:00.000Z,-12.056238,-77.06198,24.6,70,11.2,3,Nublado
2026-01-19T12:00:00.000Z,-12.056238,-77.06198,24.3,72,12.6,2,Nublado
2026-01-19T13:00:00.000Z,-12.056238,-77.06198,24.9,68,16.0,2,Nublado
2026-01-19T14:00:00.000Z,-12.056238,-77.06198,24.8,67,14.2,2,Nublado
2026-01-19T15:00:00.000Z,-12.056238,-77.06198,24.6,69,13.0,2,Nublado
2026-01-19T16:00:00.000Z,-12.056238,-77.06198,24.7,69,12.3,3,Nublado
2026-01-19T17:00:00.000Z,-12.056238,-77.06198,24.0,72,12.6,3,Nublado
2026-01-19T18:00:00.000Z,-12.056238,-77.06198,23.3,76,11.9,3,Nublado
2026-01-01T19:00:00.000Z,-12.056238,-77.06198,20.9,80,6.4,3,Nublado
2026-01-01T20:00:00.000Z,-12.056238,-77.06198,20.7,79,6.2,3,Nublado
2026-01-01T21:00:00.000Z,-12.056238,-77.06198,20.6,76,5.5,3,Nublado
2026-01-01T22:00:00.000Z,-12.056238,-77.06198,20.4,76,6.5,3,Nublado
2026-01-01T23:00:00.000Z,-12.056238,-77.06198,20.3,77,10.3,3,Nublado
2026-01-02T00:00:00.000Z,-12.056238,-77.06198,20.4,77,7.7,3,Nublado
2026-01-02T01:00:00.000Z,-12.056238,-77.06198,20.3,80,7.0,3,Nublado
2026-01-02T02:00:00.000Z,-12.056238,-77.06198,20.1,81,6.4,3,Nublado
2026-01-02T03:00:00.000Z,-12.056238,-77.06198,20.0,81,2.6,3,Nublado
2026-01-02T04:00:00.000Z,-12.056238,-77.06198,19.6,83,2.5,3,Nublado
2026-01-02T05:00:00.000Z,-12.056238,-77.06198,19.4,85,3.8,3,Nublado
2026-01-02T06:00:00.000Z,-12.056238,-77.06198,19.3,85,2.9,3,Nublado
2026-01-02T07:00:00.000Z,-12.056238,-77.06198,19.6,85,2.5,3,Nublado
2026-01-02T08:00:00.000Z,-12.056238,-77.06198,20.6,80,3.6,3,Nublado
2026-01-02T09:00:00.000Z,-12.056238,-77.06198,21.5,76,6.5,3,Nublado
2026-01-02T10:00:00.000Z,-12.056238,-77.06198,21.7,75,9.0,3,Nublado
2026-01-02T11:00:00.000Z,-12.056238,-77.06198,22.1,69,9.1,3,Nublado
2026-01-02T12:00:00.000Z,-12.056238,-77.06198,22.4,66,8.2,3,Nublado
2026-01-02T13:00:00.000Z,-12.056238,-77.06198,22.4,68,9.8,3,Nublado

In [0]:
df_spark.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(f"{catalog}.{schema}.{table}")