In [0]:
import pandas as pd
import numpy as np

In [0]:
spark.sql("USE CATALOG 'proyecto_final_prueba'")

DataFrame[]

In [0]:
catalog = spark.sql("SELECT current_catalog()").first()[0]
schema = 'silver'
table = 'weather'

In [0]:
spark.sql(f"create schema if not exists {catalog}.{schema}")

DataFrame[]

In [0]:
spark.sql(f"drop table if exists {catalog}.{schema}.{table}")

DataFrame[]

In [0]:
spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.{table} (
  fecha_hora_local TIMESTAMP,
  latitude DOUBLE,
  longitude DOUBLE,
  temperature DOUBLE,
  humidity INT,
  wind_speed DOUBLE,
  weather_code INT,
  weather_desc STRING
)
""")

DataFrame[]

In [0]:
df = spark.table(f"{catalog}.bronze.{table}").toPandas()
df

       latitude  ...  location_id
0     -6.221441  ...          NaN
1     -9.525483  ...          1.0
2    -13.673110  ...          2.0
3    -16.414762  ...          3.0
4    -13.110720  ...          4.0
...         ...  ...          ...
1195 -15.852372  ...         20.0
1196  -6.010544  ...         21.0
1197 -18.031635  ...         22.0
1198  -3.550088  ...         23.0
1199  -8.400702  ...         24.0

[1200 rows x 18 columns]

In [0]:
columns_list =['hourly.time', 'hourly.temperature_2m', 'hourly.relative_humidity_2m', 'hourly.wind_speed_10m', 'hourly.weather_code']
df_silver = df.explode(columns_list)
df_silver

      latitude  longitude  ...  hourly.weather_code  location_id
0    -6.221441  -77.88461  ...                   51          NaN
0    -6.221441  -77.88461  ...                    1          NaN
0    -6.221441  -77.88461  ...                    1          NaN
0    -6.221441  -77.88461  ...                    1          NaN
0    -6.221441  -77.88461  ...                    2          NaN
...        ...        ...  ...                  ...          ...
1199 -8.400702  -74.54935  ...                   51         24.0
1199 -8.400702  -74.54935  ...                   53         24.0
1199 -8.400702  -74.54935  ...                   51         24.0
1199 -8.400702  -74.54935  ...                   51         24.0
1199 -8.400702  -74.54935  ...                    3         24.0

[28800 rows x 18 columns]

In [0]:
rename_col = {'hourly.time': 'time',
    'hourly.temperature_2m': 'temperature',
    'hourly.relative_humidity_2m': 'humidity',
    'hourly.wind_speed_10m': 'wind_speed',
    'hourly.weather_code': 'weather_code'}

df_silver = df_silver.rename(columns=rename_col)
df_silver

      latitude  longitude  ...  weather_code  location_id
0    -6.221441  -77.88461  ...            51          NaN
0    -6.221441  -77.88461  ...             1          NaN
0    -6.221441  -77.88461  ...             1          NaN
0    -6.221441  -77.88461  ...             1          NaN
0    -6.221441  -77.88461  ...             2          NaN
...        ...        ...  ...           ...          ...
1199 -8.400702  -74.54935  ...            51         24.0
1199 -8.400702  -74.54935  ...            53         24.0
1199 -8.400702  -74.54935  ...            51         24.0
1199 -8.400702  -74.54935  ...            51         24.0
1199 -8.400702  -74.54935  ...             3         24.0

[28800 rows x 18 columns]

In [0]:
df_silver['temperature'] = df_silver['temperature'].astype(float)
df_silver['wind_speed'] = df_silver['wind_speed'].astype(float)
df_silver['humidity'] = df_silver['humidity'].astype(int)
df_silver['weather_code'] = df_silver['weather_code'].astype(int)

df_silver['fecha_hora_utc'] = pd.to_datetime(df_silver['time'])
df_silver['fecha_hora_local'] = df_silver['fecha_hora_utc'] - pd.Timedelta(hours=5)
df_silver

      latitude  longitude  ...      fecha_hora_utc    fecha_hora_local
0    -6.221441  -77.88461  ... 2026-06-25 00:00:00 2026-06-24 19:00:00
0    -6.221441  -77.88461  ... 2026-06-25 01:00:00 2026-06-24 20:00:00
0    -6.221441  -77.88461  ... 2026-06-25 02:00:00 2026-06-24 21:00:00
0    -6.221441  -77.88461  ... 2026-06-25 03:00:00 2026-06-24 22:00:00
0    -6.221441  -77.88461  ... 2026-06-25 04:00:00 2026-06-24 23:00:00
...        ...        ...  ...                 ...                 ...
1199 -8.400702  -74.54935  ... 2026-01-09 19:00:00 2026-01-09 14:00:00
1199 -8.400702  -74.54935  ... 2026-01-09 20:00:00 2026-01-09 15:00:00
1199 -8.400702  -74.54935  ... 2026-01-09 21:00:00 2026-01-09 16:00:00
1199 -8.400702  -74.54935  ... 2026-01-09 22:00:00 2026-01-09 17:00:00
1199 -8.400702  -74.54935  ... 2026-01-09 23:00:00 2026-01-09 18:00:00

[28800 rows x 20 columns]

In [0]:
condiciones = [
    (df_silver['weather_code'] == 0),
    (df_silver['weather_code'].between(1, 3)),
    (df_silver['weather_code'].between(51, 69))
]
valores = ['Despejado', 'Nublado', 'Lluvia ligera/moderada']
df_silver['weather_desc'] = np.select(condiciones, valores, default='Otro / Extremo')
df_silver

      latitude  longitude  ...    fecha_hora_local            weather_desc
0    -6.221441  -77.88461  ... 2026-06-24 19:00:00  Lluvia ligera/moderada
0    -6.221441  -77.88461  ... 2026-06-24 20:00:00                 Nublado
0    -6.221441  -77.88461  ... 2026-06-24 21:00:00                 Nublado
0    -6.221441  -77.88461  ... 2026-06-24 22:00:00                 Nublado
0    -6.221441  -77.88461  ... 2026-06-24 23:00:00                 Nublado
...        ...        ...  ...                 ...                     ...
1199 -8.400702  -74.54935  ... 2026-01-09 14:00:00  Lluvia ligera/moderada
1199 -8.400702  -74.54935  ... 2026-01-09 15:00:00  Lluvia ligera/moderada
1199 -8.400702  -74.54935  ... 2026-01-09 16:00:00  Lluvia ligera/moderada
1199 -8.400702  -74.54935  ... 2026-01-09 17:00:00  Lluvia ligera/moderada
1199 -8.400702  -74.54935  ... 2026-01-09 18:00:00                 Nublado

[28800 rows x 21 columns]

In [0]:

df_silver = df_silver.dropna(subset=['temperature'])

columnas_finales = [
    'fecha_hora_local', 'latitude', 'longitude', 'temperature', 
    'humidity', 'wind_speed', 'weather_code', 'weather_desc'
]
df_silver = df_silver[columnas_finales]
df_silver

        fecha_hora_local  latitude  ...  weather_code            weather_desc
0    2026-06-24 19:00:00 -6.221441  ...            51  Lluvia ligera/moderada
0    2026-06-24 20:00:00 -6.221441  ...             1                 Nublado
0    2026-06-24 21:00:00 -6.221441  ...             1                 Nublado
0    2026-06-24 22:00:00 -6.221441  ...             1                 Nublado
0    2026-06-24 23:00:00 -6.221441  ...             2                 Nublado
...                  ...       ...  ...           ...                     ...
1199 2026-01-09 14:00:00 -8.400702  ...            51  Lluvia ligera/moderada
1199 2026-01-09 15:00:00 -8.400702  ...            53  Lluvia ligera/moderada
1199 2026-01-09 16:00:00 -8.400702  ...            51  Lluvia ligera/moderada
1199 2026-01-09 17:00:00 -8.400702  ...            51  Lluvia ligera/moderada
1199 2026-01-09 18:00:00 -8.400702  ...             3                 Nublado

[28800 rows x 8 columns]

In [0]:
df_spark = spark.createDataFrame(df_silver)
df_spark.display()

fecha_hora_local,latitude,longitude,temperature,humidity,wind_speed,weather_code,weather_desc
2026-06-24T19:00:00.000Z,-6.221441,-77.88461,17.3,71,4.9,51,Lluvia ligera/moderada
2026-06-24T20:00:00.000Z,-6.221441,-77.88461,16.7,74,6.0,1,Nublado
2026-06-24T21:00:00.000Z,-6.221441,-77.88461,15.9,78,5.4,1,Nublado
2026-06-24T22:00:00.000Z,-6.221441,-77.88461,15.1,84,4.7,1,Nublado
2026-06-24T23:00:00.000Z,-6.221441,-77.88461,14.8,83,5.0,2,Nublado
2026-06-25T00:00:00.000Z,-6.221441,-77.88461,14.6,81,4.6,2,Nublado
2026-06-25T01:00:00.000Z,-6.221441,-77.88461,13.8,86,2.5,3,Nublado
2026-06-25T02:00:00.000Z,-6.221441,-77.88461,13.3,88,4.4,51,Lluvia ligera/moderada
2026-06-25T03:00:00.000Z,-6.221441,-77.88461,13.0,89,3.8,51,Lluvia ligera/moderada
2026-06-25T04:00:00.000Z,-6.221441,-77.88461,12.8,89,3.4,51,Lluvia ligera/moderada
2026-06-25T05:00:00.000Z,-6.221441,-77.88461,12.5,92,1.1,3,Nublado
2026-06-25T06:00:00.000Z,-6.221441,-77.88461,11.7,96,0.4,2,Nublado
2026-06-25T07:00:00.000Z,-6.221441,-77.88461,11.3,96,2.1,3,Nublado
2026-06-25T08:00:00.000Z,-6.221441,-77.88461,12.1,90,2.4,3,Nublado
2026-06-25T09:00:00.000Z,-6.221441,-77.88461,14.8,75,1.5,1,Nublado
2026-06-25T10:00:00.000Z,-6.221441,-77.88461,17.2,62,3.6,0,Despejado
2026-06-25T11:00:00.000Z,-6.221441,-77.88461,19.4,51,2.5,1,Nublado
2026-06-25T12:00:00.000Z,-6.221441,-77.88461,21.3,44,4.2,0,Despejado
2026-06-25T13:00:00.000Z,-6.221441,-77.88461,22.4,42,4.3,1,Nublado
2026-06-25T14:00:00.000Z,-6.221441,-77.88461,22.3,42,4.3,51,Lluvia ligera/moderada
2026-06-25T15:00:00.000Z,-6.221441,-77.88461,22.6,41,8.9,0,Despejado
2026-06-25T16:00:00.000Z,-6.221441,-77.88461,22.3,43,9.8,0,Despejado
2026-06-25T17:00:00.000Z,-6.221441,-77.88461,21.0,47,11.2,1,Nublado
2026-06-25T18:00:00.000Z,-6.221441,-77.88461,18.4,60,11.2,1,Nublado
2026-06-24T19:00:00.000Z,-9.525483,-77.545685,15.6,33,3.7,0,Despejado
2026-06-24T20:00:00.000Z,-9.525483,-77.545685,14.2,36,3.6,0,Despejado
2026-06-24T21:00:00.000Z,-9.525483,-77.545685,13.3,41,2.8,0,Despejado
2026-06-24T22:00:00.000Z,-9.525483,-77.545685,11.7,48,1.9,0,Despejado
2026-06-24T23:00:00.000Z,-9.525483,-77.545685,10.6,54,0.8,0,Despejado
2026-06-25T00:00:00.000Z,-9.525483,-77.545685,9.9,56,0.8,0,Despejado
2026-06-25T01:00:00.000Z,-9.525483,-77.545685,10.0,55,0.5,0,Despejado
2026-06-25T02:00:00.000Z,-9.525483,-77.545685,8.6,60,2.4,0,Despejado
2026-06-25T03:00:00.000Z,-9.525483,-77.545685,8.0,62,2.4,0,Despejado
2026-06-25T04:00:00.000Z,-9.525483,-77.545685,7.3,65,2.7,0,Despejado
2026-06-25T05:00:00.000Z,-9.525483,-77.545685,6.7,67,2.5,0,Despejado
2026-06-25T06:00:00.000Z,-9.525483,-77.545685,6.2,68,2.8,0,Despejado
2026-06-25T07:00:00.000Z,-9.525483,-77.545685,7.8,62,1.4,0,Despejado
2026-06-25T08:00:00.000Z,-9.525483,-77.545685,10.9,48,6.0,0,Despejado
2026-06-25T09:00:00.000Z,-9.525483,-77.545685,14.0,40,4.0,0,Despejado
2026-06-25T10:00:00.000Z,-9.525483,-77.545685,17.2,29,2.4,0,Despejado
2026-06-25T11:00:00.000Z,-9.525483,-77.545685,19.9,18,2.4,0,Despejado
2026-06-25T12:00:00.000Z,-9.525483,-77.545685,21.9,14,3.4,0,Despejado
2026-06-25T13:00:00.000Z,-9.525483,-77.545685,23.1,11,1.7,0,Despejado
2026-06-25T14:00:00.000Z,-9.525483,-77.545685,23.7,11,5.3,0,Despejado
2026-06-25T15:00:00.000Z,-9.525483,-77.545685,22.9,18,11.4,0,Despejado
2026-06-25T16:00:00.000Z,-9.525483,-77.545685,21.5,23,8.9,0,Despejado
2026-06-25T17:00:00.000Z,-9.525483,-77.545685,19.5,25,7.9,0,Despejado
2026-06-25T18:00:00.000Z,-9.525483,-77.545685,17.1,28,4.0,0,Despejado
2026-06-24T19:00:00.000Z,-13.67311,-72.908264,12.7,54,2.8,0,Despejado
2026-06-24T20:00:00.000Z,-13.67311,-72.908264,11.0,62,5.3,0,Despejado
2026-06-24T21:00:00.000Z,-13.67311,-72.908264,9.9,70,5.5,0,Despejado
2026-06-24T22:00:00.000Z,-13.67311,-72.908264,9.0,78,5.2,0,Despejado
2026-06-24T23:00:00.000Z,-13.67311,-72.908264,8.1,85,4.8,0,Despejado
2026-06-25T00:00:00.000Z,-13.67311,-72.908264,7.2,89,4.4,0,Despejado
2026-06-25T01:00:00.000Z,-13.67311,-72.908264,6.5,90,2.7,0,Despejado
2026-06-25T02:00:00.000Z,-13.67311,-72.908264,5.9,94,3.8,1,Nublado
2026-06-25T03:00:00.000Z,-13.67311,-72.908264,5.6,95,3.7,1,Nublado
2026-06-25T04:00:00.000Z,-13.67311,-72.908264,5.7,91,2.6,1,Nublado
2026-06-25T05:00:00.000Z,-13.67311,-72.908264,5.8,88,2.1,1,Nublado
2026-06-25T06:00:00.000Z,-13.67311,-72.908264,5.8,85,1.9,0,Despejado
2026-06-25T07:00:00.000Z,-13.67311,-72.908264,7.2,80,2.5,0,Despejado
2026-06-25T08:00:00.000Z,-13.67311,-72.908264,12.5,63,2.1,0,Despejado
2026-06-25T09:00:00.000Z,-13.67311,-72.908264,15.1,43,3.3,0,Despejado
2026-06-25T10:00:00.000Z,-13.67311,-72.908264,17.3,38,3.9,0,Despejado
2026-06-25T11:00:00.000Z,-13.67311,-72.908264,19.4,34,4.1,0,Despejado
2026-06-25T12:00:00.000Z,-13.67311,-72.908264,21.2,31,4.4,0,Despejado
2026-06-25T13:00:00.000Z,-13.67311,-72.908264,22.7,28,5.0,0,Despejado
2026-06-25T14:00:00.000Z,-13.67311,-72.908264,22.8,28,4.4,1,Nublado
2026-06-25T15:00:00.000Z,-13.67311,-72.908264,22.4,28,5.0,1,Nublado
2026-06-25T16:00:00.000Z,-13.67311,-72.908264,21.3,29,5.1,1,Nublado
2026-06-25T17:00:00.000Z,-13.67311,-72.908264,18.4,46,3.3,0,Despejado
2026-06-25T18:00:00.000Z,-13.67311,-72.908264,14.8,50,4.0,0,Despejado
2026-06-24T19:00:00.000Z,-16.414762,-71.50333,13.7,21,1.9,0,Despejado
2026-06-24T20:00:00.000Z,-16.414762,-71.50333,13.2,17,1.4,0,Despejado
2026-06-24T21:00:00.000Z,-16.414762,-71.50333,12.1,14,2.4,0,Despejado
2026-06-24T22:00:00.000Z,-16.414762,-71.50333,11.2,11,3.1,0,Despejado
2026-06-24T23:00:00.000Z,-16.414762,-71.50333,9.6,10,5.6,0,Despejado
2026-06-25T00:00:00.000Z,-16.414762,-71.50333,8.1,11,7.5,0,Despejado
2026-06-25T01:00:00.000Z,-16.414762,-71.50333,7.7,10,4.0,0,Despejado
2026-06-25T02:00:00.000Z,-16.414762,-71.50333,6.9,10,9.1,0,Despejado
2026-06-25T03:00:00.000Z,-16.414762,-71.50333,6.0,10,11.4,0,Despejado
2026-06-25T04:00:00.000Z,-16.414762,-71.50333,5.8,10,11.6,0,Despejado
2026-06-25T05:00:00.000Z,-16.414762,-71.50333,5.9,9,12.0,0,Despejado
2026-06-25T06:00:00.000Z,-16.414762,-71.50333,6.8,8,13.5,0,Despejado
2026-06-25T07:00:00.000Z,-16.414762,-71.50333,6.5,10,11.5,0,Despejado
2026-06-25T08:00:00.000Z,-16.414762,-71.50333,13.5,8,14.3,0,Despejado
2026-06-25T09:00:00.000Z,-16.414762,-71.50333,19.2,5,7.4,0,Despejado
2026-06-25T10:00:00.000Z,-16.414762,-71.50333,22.0,3,3.0,0,Despejado
2026-06-25T11:00:00.000Z,-16.414762,-71.50333,23.1,2,4.8,0,Despejado
2026-06-25T12:00:00.000Z,-16.414762,-71.50333,23.4,3,10.4,0,Despejado
2026-06-25T13:00:00.000Z,-16.414762,-71.50333,23.5,3,9.8,0,Despejado
2026-06-25T14:00:00.000Z,-16.414762,-71.50333,23.0,4,9.2,0,Despejado
2026-06-25T15:00:00.000Z,-16.414762,-71.50333,22.1,5,8.5,0,Despejado
2026-06-25T16:00:00.000Z,-16.414762,-71.50333,20.7,7,9.0,0,Despejado
2026-06-25T17:00:00.000Z,-16.414762,-71.50333,18.1,12,5.1,0,Despejado
2026-06-25T18:00:00.000Z,-16.414762,-71.50333,15.7,17,1.1,0,Despejado
2026-06-24T19:00:00.000Z,-13.11072,-74.2623,17.8,24,1.2,1,Nublado
2026-06-24T20:00:00.000Z,-13.11072,-74.2623,15.2,37,4.7,0,Despejado
2026-06-24T21:00:00.000Z,-13.11072,-74.2623,12.8,56,3.9,0,Despejado
2026-06-24T22:00:00.000Z,-13.11072,-74.2623,11.0,69,1.9,1,Nublado
2026-06-24T23:00:00.000Z,-13.11072,-74.2623,10.2,72,3.1,1,Nublado
2026-06-25T00:00:00.000Z,-13.11072,-74.2623,9.7,72,1.5,0,Despejado
2026-06-25T01:00:00.000Z,-13.11072,-74.2623,9.4,72,1.1,0,Despejado
2026-06-25T02:00:00.000Z,-13.11072,-74.2623,9.3,67,0.7,0,Despejado
2026-06-25T03:00:00.000Z,-13.11072,-74.2623,8.9,62,0.7,0,Despejado
2026-06-25T04:00:00.000Z,-13.11072,-74.2623,8.2,58,1.1,0,Despejado
2026-06-25T05:00:00.000Z,-13.11072,-74.2623,7.3,57,1.2,0,Despejado
2026-06-25T06:00:00.000Z,-13.11072,-74.2623,6.7,58,1.5,0,Despejado
2026-06-25T07:00:00.000Z,-13.11072,-74.2623,7.8,76,0.0,2,Nublado
2026-06-25T08:00:00.000Z,-13.11072,-74.2623,10.6,56,1.9,1,Nublado
2026-06-25T09:00:00.000Z,-13.11072,-74.2623,13.1,48,1.9,1,Nublado
2026-06-25T10:00:00.000Z,-13.11072,-74.2623,15.1,43,2.2,1,Nublado
2026-06-25T11:00:00.000Z,-13.11072,-74.2623,17.1,41,1.9,0,Despejado
2026-06-25T12:00:00.000Z,-13.11072,-74.2623,19.1,34,1.9,2,Nublado
2026-06-25T13:00:00.000Z,-13.11072,-74.2623,20.1,26,2.2,1,Nublado
2026-06-25T14:00:00.000Z,-13.11072,-74.2623,21.5,21,0.9,2,Nublado
2026-06-25T15:00:00.000Z,-13.11072,-74.2623,22.0,18,3.8,2,Nublado
2026-06-25T16:00:00.000Z,-13.11072,-74.2623,22.1,15,5.1,0,Despejado
2026-06-25T17:00:00.000Z,-13.11072,-74.2623,21.0,22,5.8,0,Despejado
2026-06-25T18:00:00.000Z,-13.11072,-74.2623,18.6,30,1.8,0,Despejado
2026-06-24T19:00:00.000Z,-7.2056236,-78.50253,15.2,57,4.2,0,Despejado
2026-06-24T20:00:00.000Z,-7.2056236,-78.50253,13.8,64,4.1,0,Despejado
2026-06-24T21:00:00.000Z,-7.2056236,-78.50253,13.0,71,1.9,0,Despejado
2026-06-24T22:00:00.000Z,-7.2056236,-78.50253,12.2,79,0.5,0,Despejado
2026-06-24T23:00:00.000Z,-7.2056236,-78.50253,11.1,85,1.0,0,Despejado
2026-06-25T00:00:00.000Z,-7.2056236,-78.50253,10.1,89,2.1,0,Despejado
2026-06-25T01:00:00.000Z,-7.2056236,-78.50253,9.0,97,4.2,0,Despejado
2026-06-25T02:00:00.000Z,-7.2056236,-78.50253,8.4,99,4.4,3,Nublado
2026-06-25T03:00:00.000Z,-7.2056236,-78.50253,8.4,99,4.5,3,Nublado
2026-06-25T04:00:00.000Z,-7.2056236,-78.50253,8.2,99,5.1,3,Nublado
2026-06-25T05:00:00.000Z,-7.2056236,-78.50253,7.8,99,5.9,3,Nublado
2026-06-25T06:00:00.000Z,-7.2056236,-78.50253,7.4,99,5.8,3,Nublado
2026-06-25T07:00:00.000Z,-7.2056236,-78.50253,7.8,97,7.0,3,Nublado
2026-06-25T08:00:00.000Z,-7.2056236,-78.50253,12.3,79,6.0,1,Nublado
2026-06-25T09:00:00.000Z,-7.2056236,-78.50253,16.7,55,6.3,0,Despejado
2026-06-25T10:00:00.000Z,-7.2056236,-78.50253,19.4,43,7.9,0,Despejado
2026-06-25T11:00:00.000Z,-7.2056236,-78.50253,21.6,34,6.9,0,Despejado
2026-06-25T12:00:00.000Z,-7.2056236,-78.50253,23.3,28,7.2,0,Despejado
2026-06-25T13:00:00.000Z,-7.2056236,-78.50253,24.4,25,9.3,0,Despejado
2026-06-25T14:00:00.000Z,-7.2056236,-78.50253,24.6,23,7.6,0,Despejado
2026-06-25T15:00:00.000Z,-7.2056236,-78.50253,23.8,23,1.3,0,Despejado
2026-06-25T16:00:00.000Z,-7.2056236,-78.50253,21.9,30,6.2,1,Nublado
2026-06-25T17:00:00.000Z,-7.2056236,-78.50253,19.5,48,8.7,1,Nublado
2026-06-25T18:00:00.000Z,-7.2056236,-78.50253,17.2,59,8.2,1,Nublado
2026-06-24T19:00:00.000Z,-12.056238,-77.06198,20.5,78,12.1,2,Nublado
2026-06-24T20:00:00.000Z,-12.056238,-77.06198,20.1,80,12.4,2,Nublado
2026-06-24T21:00:00.000Z,-12.056238,-77.06198,19.9,81,12.3,2,Nublado
2026-06-24T22:00:00.000Z,-12.056238,-77.06198,19.8,82,12.5,3,Nublado
2026-06-24T23:00:00.000Z,-12.056238,-77.06198,19.5,84,13.2,3,Nublado
2026-06-25T00:00:00.000Z,-12.056238,-77.06198,19.0,86,13.6,2,Nublado
2026-06-25T01:00:00.000Z,-12.056238,-77.06198,18.7,86,9.5,1,Nublado
2026-06-25T02:00:00.000Z,-12.056238,-77.06198,18.5,87,11.4,1,Nublado
2026-06-25T03:00:00.000Z,-12.056238,-77.06198,18.5,87,10.7,1,Nublado
2026-06-25T04:00:00.000Z,-12.056238,-77.06198,18.4,88,11.3,1,Nublado
2026-06-25T05:00:00.000Z,-12.056238,-77.06198,18.3,87,10.9,1,Nublado
2026-06-25T06:00:00.000Z,-12.056238,-77.06198,18.3,87,11.3,1,Nublado
2026-06-25T07:00:00.000Z,-12.056238,-77.06198,18.6,86,9.9,1,Nublado
2026-06-25T08:00:00.000Z,-12.056238,-77.06198,19.5,80,11.5,1,Nublado
2026-06-25T09:00:00.000Z,-12.056238,-77.06198,20.6,73,11.5,1,Nublado
2026-06-25T10:00:00.000Z,-12.056238,-77.06198,21.6,69,11.7,2,Nublado
2026-06-25T11:00:00.000Z,-12.056238,-77.06198,22.4,67,11.8,2,Nublado
2026-06-25T12:00:00.000Z,-12.056238,-77.06198,22.6,66,13.3,1,Nublado
2026-06-25T13:00:00.000Z,-12.056238,-77.06198,23.0,64,13.9,2,Nublado
2026-06-25T14:00:00.000Z,-12.056238,-77.06198,22.5,66,15.8,1,Nublado
2026-06-25T15:00:00.000Z,-12.056238,-77.06198,22.0,68,16.5,2,Nublado
2026-06-25T16:00:00.000Z,-12.056238,-77.06198,21.2,72,18.3,2,Nublado
2026-06-25T17:00:00.000Z,-12.056238,-77.06198,20.3,77,18.7,2,Nublado
2026-06-25T18:00:00.000Z,-12.056238,-77.06198,19.9,77,17.0,1,Nublado
2026-06-24T19:00:00.000Z,-13.532513,-71.95053,11.3,48,8.2,0,Despejado
2026-06-24T20:00:00.000Z,-13.532513,-71.95053,10.0,63,6.5,0,Despejado
2026-06-24T21:00:00.000Z,-13.532513,-71.95053,8.6,71,4.0,0,Despejado
2026-06-24T22:00:00.000Z,-13.532513,-71.95053,7.4,77,3.1,0,Despejado
2026-06-24T23:00:00.000Z,-13.532513,-71.95053,6.3,83,2.6,0,Despejado
2026-06-25T00:00:00.000Z,-13.532513,-71.95053,5.2,89,2.2,0,Despejado
2026-06-25T01:00:00.000Z,-13.532513,-71.95053,4.4,91,1.8,0,Despejado
2026-06-25T02:00:00.000Z,-13.532513,-71.95053,3.6,92,0.2,0,Despejado
2026-06-25T03:00:00.000Z,-13.532513,-71.95053,2.7,95,0.5,0,Despejado
2026-06-25T04:00:00.000Z,-13.532513,-71.95053,2.0,98,0.9,0,Despejado
2026-06-25T05:00:00.000Z,-13.532513,-71.95053,1.4,99,0.7,0,Despejado
2026-06-25T06:00:00.000Z,-13.532513,-71.95053,0.9,99,0.9,0,Despejado
2026-06-25T07:00:00.000Z,-13.532513,-71.95053,1.2,96,0.6,1,Nublado
2026-06-25T08:00:00.000Z,-13.532513,-71.95053,4.9,77,1.3,0,Despejado
2026-06-25T09:00:00.000Z,-13.532513,-71.95053,9.1,56,2.3,0,Despejado
2026-06-25T10:00:00.000Z,-13.532513,-71.95053,12.0,43,3.1,0,Despejado
2026-06-25T11:00:00.000Z,-13.532513,-71.95053,14.2,35,4.1,0,Despejado
2026-06-25T12:00:00.000Z,-13.532513,-71.95053,15.9,29,3.8,0,Despejado
2026-06-25T13:00:00.000Z,-13.532513,-71.95053,16.9,24,3.1,0,Despejado
2026-06-25T14:00:00.000Z,-13.532513,-71.95053,17.8,21,3.6,0,Despejado
2026-06-25T15:00:00.000Z,-13.532513,-71.95053,17.8,19,3.8,0,Despejado
2026-06-25T16:00:00.000Z,-13.532513,-71.95053,17.4,18,4.1,0,Despejado
2026-06-25T17:00:00.000Z,-13.532513,-71.95053,16.0,21,4.4,1,Nublado
2026-06-25T18:00:00.000Z,-13.532513,-71.95053,13.4,28,2.9,0,Despejado
2026-06-24T19:00:00.000Z,-12.688928,-74.91846,8.3,55,1.0,0,Despejado
2026-06-24T20:00:00.000Z,-12.688928,-74.91846,7.2,60,0.7,0,Despejado
2026-06-24T21:00:00.000Z,-12.688928,-74.91846,6.3,65,1.1,0,Despejado
2026-06-24T22:00:00.000Z,-12.688928,-74.91846,5.4,76,1.0,0,Despejado
2026-06-24T23:00:00.000Z,-12.688928,-74.91846,4.5,82,0.3,0,Despejado
2026-06-25T00:00:00.000Z,-12.688928,-74.91846,3.7,80,0.3,0,Despejado
2026-06-25T01:00:00.000Z,-12.688928,-74.91846,2.5,77,0.3,0,Despejado
2026-06-25T02:00:00.000Z,-12.688928,-74.91846,1.5,66,1.5,0,Despejado
2026-06-25T03:00:00.000Z,-12.688928,-74.91846,0.6,54,1.4,0,Despejado
2026-06-25T04:00:00.000Z,-12.688928,-74.91846,-0.3,52,1.8,0,Despejado
2026-06-25T05:00:00.000Z,-12.688928,-74.91846,-1.1,56,2.1,0,Despejado
2026-06-25T06:00:00.000Z,-12.688928,-74.91846,-1.5,58,2.3,0,Despejado
2026-06-25T07:00:00.000Z,-12.688928,-74.91846,0.2,58,3.4,0,Despejado
2026-06-25T08:00:00.000Z,-12.688928,-74.91846,4.2,52,2.7,0,Despejado
2026-06-25T09:00:00.000Z,-12.688928,-74.91846,7.0,49,3.9,0,Despejado
2026-06-25T10:00:00.000Z,-12.688928,-74.91846,9.6,40,6.1,0,Despejado
2026-06-25T11:00:00.000Z,-12.688928,-74.91846,11.2,38,7.8,0,Despejado
2026-06-25T12:00:00.000Z,-12.688928,-74.91846,12.6,33,7.7,1,Nublado
2026-06-25T13:00:00.000Z,-12.688928,-74.91846,13.2,28,6.5,2,Nublado
2026-06-25T14:00:00.000Z,-12.688928,-74.91846,14.0,28,7.1,2,Nublado
2026-06-25T15:00:00.000Z,-12.688928,-74.91846,14.0,27,6.9,2,Nublado
2026-06-25T16:00:00.000Z,-12.688928,-74.91846,13.6,25,8.2,2,Nublado
2026-06-25T17:00:00.000Z,-12.688928,-74.91846,12.3,34,5.6,1,Nublado
2026-06-25T18:00:00.000Z,-12.688928,-74.91846,9.5,41,3.0,1,Nublado
2026-06-24T19:00:00.000Z,-9.876977,-76.23251,18.4,77,2.4,0,Despejado
2026-06-24T20:00:00.000Z,-9.876977,-76.23251,17.7,80,2.9,2,Nublado
2026-06-24T21:00:00.000Z,-9.876977,-76.23251,16.6,86,2.4,3,Nublado
2026-06-24T22:00:00.000Z,-9.876977,-76.23251,16.1,89,1.5,3,Nublado
2026-06-24T23:00:00.000Z,-9.876977,-76.23251,15.9,90,1.3,3,Nublado
2026-06-25T00:00:00.000Z,-9.876977,-76.23251,15.5,93,1.1,2,Nublado
2026-06-25T01:00:00.000Z,-9.876977,-76.23251,14.8,97,0.2,2,Nublado
2026-06-25T02:00:00.000Z,-9.876977,-76.23251,13.9,98,1.5,3,Nublado
2026-06-25T03:00:00.000Z,-9.876977,-76.23251,13.1,100,1.1,3,Nublado
2026-06-25T04:00:00.000Z,-9.876977,-76.23251,12.7,99,1.6,51,Lluvia ligera/moderada
2026-06-25T05:00:00.000Z,-9.876977,-76.23251,12.3,100,1.8,51,Lluvia ligera/moderada
2026-06-25T06:00:00.000Z,-9.876977,-76.23251,11.8,100,1.4,3,Nublado
2026-06-25T07:00:00.000Z,-9.876977,-76.23251,12.4,94,2.9,3,Nublado
2026-06-25T08:00:00.000Z,-9.876977,-76.23251,15.1,80,1.5,2,Nublado
2026-06-25T09:00:00.000Z,-9.876977,-76.23251,17.8,70,1.9,1,Nublado
2026-06-25T10:00:00.000Z,-9.876977,-76.23251,20.1,62,2.2,1,Nublado
2026-06-25T11:00:00.000Z,-9.876977,-76.23251,22.4,53,1.8,0,Despejado
2026-06-25T12:00:00.000Z,-9.876977,-76.23251,24.3,46,3.3,0,Despejado
2026-06-25T13:00:00.000Z,-9.876977,-76.23251,25.0,43,7.1,1,Nublado
2026-06-25T14:00:00.000Z,-9.876977,-76.23251,24.5,49,10.6,51,Lluvia ligera/moderada
2026-06-25T15:00:00.000Z,-9.876977,-76.23251,23.3,54,10.8,51,Lluvia ligera/moderada
2026-06-25T16:00:00.000Z,-9.876977,-76.23251,22.3,59,10.0,0,Despejado
2026-06-25T17:00:00.000Z,-9.876977,-76.23251,20.7,65,9.2,0,Despejado
2026-06-25T18:00:00.000Z,-9.876977,-76.23251,18.5,76,5.0,0,Despejado
2026-06-24T19:00:00.000Z,-14.094903,-75.719574,19.2,67,1.8,1,Nublado
2026-06-24T20:00:00.000Z,-14.094903,-75.719574,17.7,72,2.3,0,Despejado
2026-06-24T21:00:00.000Z,-14.094903,-75.719574,16.5,76,2.8,0,Despejado
2026-06-24T22:00:00.000Z,-14.094903,-75.719574,15.5,81,4.5,0,Despejado
2026-06-24T23:00:00.000Z,-14.094903,-75.719574,14.4,87,4.5,0,Despejado
2026-06-25T00:00:00.000Z,-14.094903,-75.719574,13.4,92,7.0,0,Despejado
2026-06-25T01:00:00.000Z,-14.094903,-75.719574,13.2,93,3.6,0,Despejado
2026-06-25T02:00:00.000Z,-14.094903,-75.719574,12.5,96,8.1,0,Despejado
2026-06-25T03:00:00.000Z,-14.094903,-75.719574,11.7,100,9.2,3,Nublado
2026-06-25T04:00:00.000Z,-14.094903,-75.719574,11.3,100,8.6,3,Nublado
2026-06-25T05:00:00.000Z,-14.094903,-75.719574,11.2,99,8.6,3,Nublado
2026-06-25T06:00:00.000Z,-14.094903,-75.719574,11.0,100,8.1,3,Nublado
2026-06-25T07:00:00.000Z,-14.094903,-75.719574,11.3,94,5.2,3,Nublado
2026-06-25T08:00:00.000Z,-14.094903,-75.719574,11.6,99,7.4,3,Nublado
2026-06-25T09:00:00.000Z,-14.094903,-75.719574,12.7,94,4.9,3,Nublado
2026-06-25T10:00:00.000Z,-14.094903,-75.719574,15.9,73,3.8,3,Nublado
2026-06-25T11:00:00.000Z,-14.094903,-75.719574,18.2,63,5.2,2,Nublado
2026-06-25T12:00:00.000Z,-14.094903,-75.719574,20.7,54,4.6,0,Despejado
2026-06-25T13:00:00.000Z,-14.094903,-75.719574,22.8,46,6.2,0,Despejado
2026-06-25T14:00:00.000Z,-14.094903,-75.719574,24.3,42,8.6,0,Despejado
2026-06-25T15:00:00.000Z,-14.094903,-75.719574,24.9,41,9.6,0,Despejado
2026-06-25T16:00:00.000Z,-14.094903,-75.719574,24.5,42,7.8,0,Despejado
2026-06-25T17:00:00.000Z,-14.094903,-75.719574,23.1,46,8.3,0,Despejado
2026-06-25T18:00:00.000Z,-14.094903,-75.719574,20.7,55,1.1,0,Despejado
2026-06-24T19:00:00.000Z,-12.056238,-75.20215,13.5,58,3.2,3,Nublado
2026-06-24T20:00:00.000Z,-12.056238,-75.20215,12.8,64,1.4,2,Nublado
2026-06-24T21:00:00.000Z,-12.056238,-75.20215,11.2,69,2.3,3,Nublado
2026-06-24T22:00:00.000Z,-12.056238,-75.20215,10.2,73,1.4,1,Nublado
2026-06-24T23:00:00.000Z,-12.056238,-75.20215,9.1,78,0.5,0,Despejado
2026-06-25T00:00:00.000Z,-12.056238,-75.20215,7.8,84,0.8,0,Despejado
2026-06-25T01:00:00.000Z,-12.056238,-75.20215,7.7,76,2.9,0,Despejado
2026-06-25T02:00:00.000Z,-12.056238,-75.20215,6.8,80,2.2,0,Despejado
2026-06-25T03:00:00.000Z,-12.056238,-75.20215,6.2,83,3.2,0,Despejado
2026-06-25T04:00:00.000Z,-12.056238,-75.20215,5.6,85,3.3,0,Despejado
2026-06-25T05:00:00.000Z,-12.056238,-75.20215,5.1,87,3.6,0,Despejado
2026-06-25T06:00:00.000Z,-12.056238,-75.20215,4.5,88,3.1,0,Despejado
2026-06-25T07:00:00.000Z,-12.056238,-75.20215,5.6,82,3.1,0,Despejado
2026-06-25T08:00:00.000Z,-12.056238,-75.20215,7.7,74,4.3,1,Nublado
2026-06-25T09:00:00.000Z,-12.056238,-75.20215,10.0,68,4.2,0,Despejado
2026-06-25T10:00:00.000Z,-12.056238,-75.20215,12.1,56,4.6,0,Despejado
2026-06-25T11:00:00.000Z,-12.056238,-75.20215,14.1,42,5.1,0,Despejado
2026-06-25T12:00:00.000Z,-12.056238,-75.20215,16.4,27,6.9,0,Despejado
2026-06-25T13:00:00.000Z,-12.056238,-75.20215,18.1,22,10.2,0,Despejado
2026-06-25T14:00:00.000Z,-12.056238,-75.20215,18.8,23,9.9,0,Despejado
2026-06-25T15:00:00.000Z,-12.056238,-75.20215,19.1,15,10.5,2,Nublado
2026-06-25T16:00:00.000Z,-12.056238,-75.20215,18.7,10,10.5,2,Nublado
2026-06-25T17:00:00.000Z,-12.056238,-75.20215,17.4,18,10.1,3,Nublado

In [0]:
df_spark.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(f"{catalog}.{schema}.{table}")